# docker-compose.yml
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: satcom_ai
      MYSQL_USER: satcom_user
      MYSQL_PASSWORD: secure_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=satcom_user
      - DB_PASSWORD=secure_password
      - DB_NAME=satcom_ai
      - AI_MODEL_PATH=/satcom-ai/models/cnn_denoiser.keras
    volumes:
      - ./models:/satcom-ai/models
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  mysql_data: